services:
  postgres:
    image: postgres:15.2-bullseye
    environment:
      - POSTGRES_USER=faildeck
      - POSTGRES_PASSWORD=imasecretipromise
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: